
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0'
version_full = '519b740ca2c67f0ba4c2758ed1c17f11df561ee7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

